package bean;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import utils.DBUtilsGiaoVien;

/**
 * BaiHoc generated by hbm2java
 */
public class BaiHoc implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String maBaiHoc;
	private String maKhoaHoc;
	private String tenBaiHoc;
	private String moTaNoiDung;
	
	public BaiHoc() {
	}

	public BaiHoc(String maBaiHoc) {
		this.maBaiHoc = maBaiHoc;
	}

	public BaiHoc(String maBaiHoc, String khoaHoc, String tenBaiHoc, String moTaNoiDung) {
		this.maBaiHoc = maBaiHoc;
		this.maKhoaHoc = khoaHoc;
		this.tenBaiHoc = tenBaiHoc;
		this.moTaNoiDung = moTaNoiDung;
	}
	
	public String autoID(Connection conn) throws SQLException
	{
		String sql = "SELECT * FROM BaiHoc";
		
		PreparedStatement pstm=null;
		try {
			pstm = conn.prepareStatement(sql);
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
        ResultSet rs = pstm.executeQuery();
        String kqString="";
        while (rs.next()) 
        {
        	kqString= rs.getString("MaBaiHoc");
        }
        
        int soluong = Integer.parseInt(kqString.substring(2));
    	if (soluong+1<10)
    		kqString= "BH000"+ String.valueOf(soluong+1);
    	else {
			kqString= "BH00"+ String.valueOf(soluong+1);
		}
        
        return kqString;  
	}
	
	public void addBaiHoc(Connection conn) throws SQLException
	{
		DBUtilsGiaoVien.ThemBaiHoc(conn, this);
	}
	
	public BaiHoc(Connection conn,String khoaHoc, String tenBaiHoc, String moTaNoiDung) throws SQLException {
		this.maBaiHoc = autoID(conn);
		this.maKhoaHoc = khoaHoc;
		this.tenBaiHoc = tenBaiHoc;
		this.moTaNoiDung = moTaNoiDung;
		addBaiHoc(conn);
		
	}

	public String getMaBaiHoc() {
		return this.maBaiHoc;
	}

	public void setMaBaiHoc(String maBaiHoc) {
		this.maBaiHoc = maBaiHoc;
	}

	public String getMaKhoaHoc() {
		return this.maKhoaHoc;
	}

	public void setMaKhoaHoc(String khoaHoc) {
		this.maKhoaHoc = khoaHoc;
	}

	public String getTenBaiHoc() {
		return this.tenBaiHoc;
	}

	public void setTenBaiHoc(String tenBaiHoc) {
		this.tenBaiHoc = tenBaiHoc;
	}

	public String getMoTaNoiDung() {
		return this.moTaNoiDung;
	}

	public void setMoTaNoiDung(String moTaNoiDung) {
		this.moTaNoiDung = moTaNoiDung;
	}


}
