package bean;
import java.sql.Date;

/**
 * TaiNguyen generated by hbm2java
 */
public class TaiNguyen implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String maTaiNguyen;
	private BaiHoc baiHoc;
	private String tenTaiNguyen;
	private Date ngayCapNhat;
	private String noiDung;

	public TaiNguyen() {
	}

	public TaiNguyen(String maTaiNguyen) {
		this.maTaiNguyen = maTaiNguyen;
	}

	public TaiNguyen(String maTaiNguyen, BaiHoc baiHoc, String tenTaiNguyen, Date ngayCapNhat,
			String noiDung) {
		this.maTaiNguyen = maTaiNguyen;
		this.baiHoc = baiHoc;
		this.tenTaiNguyen = tenTaiNguyen;
		this.ngayCapNhat = ngayCapNhat;
		this.noiDung = noiDung;
	}

	public String getMaTaiNguyen() {
		return this.maTaiNguyen;
	}

	public void setMaTaiNguyen(String maTaiNguyen) {
		this.maTaiNguyen = maTaiNguyen;
	}

	public BaiHoc getBaiHoc() {
		return this.baiHoc;
	}

	public void setBaiHoc(BaiHoc baiHoc) {
		this.baiHoc = baiHoc;
	}

	public String getTenTaiNguyen() {
		return this.tenTaiNguyen;
	}

	public void setTenTaiNguyen(String tenTaiNguyen) {
		this.tenTaiNguyen = tenTaiNguyen;
	}

	public Date getNgayCapNhat() {
		return this.ngayCapNhat;
	}

	public void setNgayCapNhat(Date ngayCapNhat) {
		this.ngayCapNhat = ngayCapNhat;
	}

	public String getNoiDung() {
		return this.noiDung;
	}

	public void setNoiDung(String noiDung) {
		this.noiDung = noiDung;
	}

}
